[package]
name = "vector_toml"
version = "0.1.4"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/toml.rs"
crate-type = ["cdylib"]

[dependencies]
vector_extension_api = { path = "../../crates/extension_api" }
