[package]
name = "zed_glsl"
version = "0.2.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/glsl.rs"
crate-type = ["cdylib"]

[dependencies]
vector_extension_api = { path = "../../crates/extension_api" }
