[package]
name = "vector_emmet"
version = "0.0.3"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/emmet.rs"
crate-type = ["cdylib"]

[dependencies]
vector_extension_api = { path = "../../crates/extension_api" }
