[package]
name = "zed_proto"
version = "0.3.1"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/proto.rs"
crate-type = ["cdylib"]

[dependencies]
vector_extension_api = { path = "../../crates/extension_api" }
